# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EMBER Medical' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EMBER Medical

  target 'EMBER MedicalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
