name: CI
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - develop
      - feature/*

jobs:
  build:
    runs-on: macos
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.app
      - name: List Files
        run: |
          ls
          cd src
          ls
      - name: Install Dependencies
        run: |
          cd src/EMBER\ Medical;pod install
        shell: bash
      - name: Build & Test
        run: |
          xcrun xcodebuild -workspace "src/EMBER\ Medical/EMBER\ Medical.xcworkspace" -scheme "EMBER Medical" -sdk "iphoneos13.1" -destination "platform=iOS Simulator,OS=13.1,name=iPhone 8" -configuration Debug RUN_UNIT_TEST_WITH_IOS_SIM=NO TEST_AFTER_BUILD=YES -enableCodeCoverage YES clean build test
