name: CI
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - develop
      - feature/*

jobs:
  build:
    runs-on: macos
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.app
      - name: List Files
        run: |
          ls
          cd src
          ls
      - name: Install Dependencies
        run: |
          cd src/EMBER\ Medical;pod install
        shell: bash
      - name: Build & Test
        run: |
          cd src/EMBER\ Medical
          xcodebuild clean build test -workspace "EMBER Medical.xcworkspace" -scheme "EMBER Medical" -destination "platform=iOS Simulator,OS=13.2,name=iPhone 8" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          scheme: $
          destination: $
